<?php
/**
* @file trebutra.module
* Trello Bug Tracker
* @author Matt Withoos <mattwithoos@gmail.com>
* @link http://mattwithoos.com
*/

function trebutra_theme($existing, $type, $theme, $path) {
  return array(
      'trebutra' => array(
        'template' => 'trebutra',
     ),
  );
}

function trebutra_help($path, $arg) {
  switch ($path) {
    case "admin/help#trebutra":
      return '<p>' . t("Integrates Trello as a Bug Tracker") . '</p>';
      break;
  }
}

function trebutra_block_info() {
  $blocks['trebutra'] = array(
    // The name that will appear in the block list.
    'info' => t('Trello Bug Tracker'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

function trebutra_block_view($delta='') {
  $block = array();
  switch($delta) {
      case 'trebutra' :
            $content = theme('trebutra');
            $block['content'] = $content;
      break;
  }
  return $block;
}

function trebutra_menu() {
  $items = array();
  $items['admin/config/content/trebutra'] = array(
    'title' => 'Trebutra',
    'description' => 'Configuration for Trebutra (Trello Bug Tracker) module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('trebutra_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function trebutra_form($form, &$form_state) {
  $form['trebutra_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Trello API Key'),
    '#default_value' => variable_get('trebutra_key'),
    '#description' => t('Obtained via the Trello API page'),
    '#required' => TRUE
  );
  $form['trebutra_apiend'] = array(
    '#type' => 'textfield',
    '#title' => t('Trello API endpoint'),
    '#default_value' => variable_get('trebutra_apiend', 'https://api.trello.com/1'),
    '#description' => t('Usually https://api.trello.com/1'),
    '#required' => TRUE
  );
  $form['trebutra_listid'] = array(
    '#type' => 'textfield',
    '#title' => t('Trello List ID'),
    '#default_value' => variable_get('trebutra_listid'),
    '#description' => t('The list ID you want cards to go to on Trello. Go to Export on Trello and click JSON and look for idList and enter that value here.'),
    '#required' => TRUE
  );
  $form['trebutra_token'] = array(
    '#type' => 'textfield',
    '#title' => t('Trello API token'),
    '#default_value' => variable_get('trebutra_token'),
    '#description' => t('Get a token by substituting your API key and a made-up app name into this URL (https://trello.com/1/connect?key=apikeygoeshere&name=appnamegoeshere&response_type=token&scope=read,write&expiration=never) and visiting it in your browser.'),
    '#required' => TRUE
  );
  $form['trebutra_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Report recipient email'),
    '#default_value' => variable_get('trebutra_email'),
    '#description' => t('If you would like reports, enter an email here and tick the box below')
  );
  $form['trebutra_emailsend'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable report emails'),
    '#default_value' => variable_get('trebutra_emailsend', 1),
    '#description' => t('If you would like reports, enter an email here and tick the box below'),
    '#attributes' => array('checked' => 'checked')
  );
  return system_settings_form($form);
}

